name: "Discussion / General Feedback"
description: "Discuss any recent / planned changes to the platform"
body:
  - type: textarea
    id: topic
    attributes:
      label: "What topic do you want to discuss?"
      description: "Brief description of the topic. Is this megathread for a recently added major feature? Or is this general discussion for a planned feature set? Or perhaps some social implications / concerns?"
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: "Goal of discussion"
      description: "Are you hoping to help shape some future features? Or want to discuss potential solutions to complex problems, but not sure how this would be approached? Or do you want to suggest some alterations to the current priorities/roadmap?"
    validations:
      required: true
  - type: textarea
    id: discussion
    attributes:
      label: "Discussion:"
      placeholder: "Start the full discussion here."
    validations:
      required: true
